### ISSUE TITLE
[BUG][chat]

### ISSUE THREAD

**Issue by Blessian** [SEP-proj/AI#14]
## Description
버그 수정에 관한 이슈 템플릿입니다.

---

## TODO
- [ ]  링크 제공 기능 호출시 500오류가 나는 문제
- [ ]  링크을 하나만 제공하는 문제
- [ ]  json 형식 문제

---

## ETC

---
* 기타사항을 작성한다.
