### ISSUE TITLE
[FEATURE][topic_recommand] 최신 이슈 적용

### ISSUE THREAD

**Issue by narae3759** [SEP-proj/AI#4]
## Description
챗봇에게 최신 이슈를 입력하기 위해 업데이트 시점에서 이전 7일의 이슈 파일을 만들어 학습시킵니다.

---

## TODO
- [ ]  BeautifulSoup을 통해 '네이버 뉴스' 크롤링
- [ ]  Kmeans 클러스터링 후 크기 순 군집 5개 추출 
- [ ]  5개 키워드에 대한 뉴스 본문을 챗봇에게 학습

---

## ETC

---
* 크롤링 기준은 업데이트 시점 일주일 전으로 한다.
