### ISSUE TITLE
[FEATURE][modification] 어색한 문장 찾기

### ISSUE THREAD

**Issue by narae3759** [SEP-proj/AI#6]
## Description
글 작성의 마지막 단계에서 최종적으로 어색한 곳이 없는지 확인하는 기능입니다.

---

## TODO
- [ ]  mistake, reason, advice에 맞추어 리스트로 출력한다.
- [ ]  교정할 곳이 없는 경우에는 빈 리스트로 출력한다. 
- [ ]  앞의 기능들과 말투를 통일시킨다.

---

## ETC

---
